units:
  kx: cx
  ky: cy
  px: kx + 4
  py: ky + 4
points:
  key:
    padding: ky
    spread: kx
    tags:
      1u: true
  zones:
    main:
      key.tags:
        - key
      anchor.shift: [150, -150]
      rows:
        bottom:
        home:
        top:
      columns:
        pinkie:
          key:
            spread: kx
            splay: 18
          rows:
            top:
              column_net: P0
            home:
              column_net: P6
            bottom:
              column_net: P1
        ring:
          key:
            spread: kx
            splay: -10
            origin: [-12, -11]
            stagger: 10
          rows:
            top:
              column_net: P3
            home:
              column_net: P4
            bottom:
              column_net: P5
        middle:
          key:
            spread: kx+2
            stagger: 10
            splay: -3
          rows:
            top:
              column_net: P16
            home:
              column_net: P10
            bottom:
              column_net: P2
        index:
          key:
            spread: kx+1
            stagger: -6
            splay: -5
          rows:
            top:
              column_net: P18
            home:
              column_net: P15
            bottom:
              column_net: P14
        far:
          key:
            spread: kx
            stagger: -8
          rows:
            top:
              column_net: P21
            home:
              column_net: P20
            bottom:
              column_net: P19
    thumb:
      key.tags:
        - key
      anchor:
        ref: main_index_bottom
        shift: [19, -30]
      rows:
      columns:
        inner:
          key:
            column_net: P9
        middle:
          key:
            splay: -28
            spread: kx+4
            stagger: -5
            column_net: P7
        outer:
          key:
            splay: -28
            spread: kx+4
            stagger: -5
            column_net: P8
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: main_pinkie_top
          shift: [-0.5px, 0.5py]
        - ref: main_pinkie_top
          shift: [0.7px, 0.5py]
        - ref: main_ring_top
          shift: [-0.5px, 0.5py]
        - ref: main_ring_top
          shift: [0.5px, 0.5py]
        - ref: main_middle_top
          shift: [-0.5px, 0.5py]
        - ref: main_middle_top
          shift: [0.5px, 0.5py]
        - ref: main_index_top
          shift: [-0.5px, 0.5py]
        - ref: main_index_top
          shift: [0.5px, 0.5py]
        - ref: main_far_top
          shift: [-7, 0.5py]
        - ref: main_far_top
          shift: [1.6px, 0.5py]
        - ref: main_far_bottom
          shift: [1.6px, -0.5py]
        - ref: thumb_outer
          shift: [-0.5px, 0.5py]
        - ref: thumb_outer
          shift: [0.5px, 0.5py]
        - ref: thumb_outer
          shift: [0.5px, -0.5py]
        - ref: thumb_middle
          shift: [0.4px, -0.5py]
        - ref: thumb_inner
          shift: [0.4px, -0.5py]
        - ref: thumb_inner
          shift: [-0.5px, -0.5py]
        - ref: thumb_inner
          shift: [-0.5px, -3]
        - ref: main_pinkie_bottom
          shift: [-0.5px, -0.5py]
      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  AlcoKeb:
    outlines:
      board:
        outline: board
      keycaps:
        outline: keys
        layer: Eco1.user

    footprints:
      switch:
        what: ceoloide/switch_choc_v1_v2
        where: /key/
        params:
          from: "{{column_net}}"
          to: "GND"
          reversible: true
          hotswap: true
      nice_nano:
        what: ceoloide/mcu_nice_nano
        where:
          ref: main_far_top
          shift: [24,-7]
        params:
          reversible: true
          side: B
      reset:
        what: ceoloide/reset_switch_tht_top
        where:
          ref: main_far_top
          shift: [12, 0]
          rotate: -90
        params:
          reversible: true
      power_switch:
        what: ceoloide/power_switch_smd_side
        where:
          ref: main_far_bottom
          shift: [1.53px, -5]
        params:
          reversible: true
      power_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: main_far_home
          shift: [18, -14]
          rotate: 90
        params:
          reversible: true